defaultSourceData: "file"           # for import of data
defaultSourceModel: "file"           # for import of models
fileExtension: "bmsc"      # for download of models
rPackageName: "BMSCApp"       # for download and import of models
