defaultSourceData: "file"           # for import of data
defaultSourceModel: "file"           # for import of models
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "xls"
  - "xlsx"
  - "csv"
  - "odt"
  - "txt"
ckanModelTypes:
  - "zip"
  - "bmsc"
githubRepo: "bmsc-app"        # for import of models
fileExtension: "bmsc"      # for download of models
rPackageName: "BMSCApp"       # for download and import of models
